services:
  postgres:
    image: postgres:15-alpine
    container_name: link-shortener-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=link_shortener
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: link-shortener-app
    build: .
    ports:
      - "8080:8080"
    environment:
      #- SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/link_shortener
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .:/app
      - /app/target
    depends_on:
      - postgres
    command: ./mvnw spring-boot:run

volumes:
  postgres-data: