services:
  postgres:
    image: postgres:15-alpine
    container_name: link-shortener-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=link_shortener
    volumes:
      - postgres-data:/var/lib/postgresql/data

  db_adminer_2:
    container_name: db_adminer_2
    image: adminer
    restart: always
    ports:
      - '8081:8080'

volumes:
  postgres-data: